Implement data into DB and View
jgabriele/otamatone.fr pull request #17
Opened 2019-07-22 12:49 UTC by Thibaut06

Big implementation of data into DB and view

2019-07-22 12:51 UTC, lboukaya submitted a review, later dismissed
OK !

2019-07-23 21:11 UTC, jgabriele requested changes
Des p'tits trucs à clean mais sinon c'est bien :).

Autre chose avant que j'oublie. Est-ce que tu peux versionner (=== mettre sur git, dans ce projet) les `.json` des données de la DB ? Comme ça je les ai directement sur le serveur.

Un exercice pour aller plus loin: tu as 4 fonctions qui se ressemblent vraiment beaucoup. Est-ce qu'il y a moyen d'en avoir une seule, qui aurait un paramètre en plus pour définir quel type de donnée elle reçoit ?

2019-07-23 21:11 UTC, jgabriele commented on app.js
> +            //console.log("Les données des videos ", renderVideos)
Tu peux enlever ces commentaires :)

2019-07-23 21:11 UTC, jgabriele commented on app.js
> +        dbo.collection("courses").find().toArray(getDataCourses)
Pourquoi pas de `limit(3)` pour eux ?

2019-07-24 07:35 UTC, Thibaut06 commented on app.js
> +        dbo.collection("courses").find().toArray(getDataCourses)
Parce que j'ai que trois documents dans les collections (courses, posts et articles)

2019-07-25 09:47 UTC, jgabriele commented on app.js
> +        dbo.collection("courses").find().toArray(getDataCourses)
... Pour l'instant :). Mais si un jour on en a 4, on va en afficher 4 sur la page d'accueil et c'est pas bon

2019-07-26 08:53 UTC, jgabriele approved these changes

2019-07-26 08:53 UTC, merged