New update
jgabriele/otamatone.fr pull request #19
Opened 2019-07-30 08:05 UTC by Thibaut06

implement shopping page and user avatar

2019-07-30 08:40 UTC, jgabriele requested changes
Quelques commentaires. Si t'as des questions, n'hésite pas :)

PS: met un titre plus explicite pour tes PRs. Si dans 6 mois on se dit "merde quand est-ce qu'il avait rajouté la partie Shop déjà, il avait fait un truc cool j'voulais voir comment il avait fait" on est niqués ^^.

2019-07-30 08:40 UTC, jgabriele commented on app.js
> +app.get("/", (request, response) => {
Owwwww yeah ! ❤️

2019-07-30 08:40 UTC, jgabriele commented on app.js
> +        dbo.collection("articles").find().limit(3).toArray(getDataArticles)
Pourquoi ne pas aussi limiter les 2 autres calls au dessus ?

2019-07-30 08:40 UTC, jgabriele commented on app.js
> +    MongoClient.connect(url, param, (err, db) => {
J'avais pas fait gaffe que t'avais fait jusqu'à présent, mais en gros ce que t'es en train de faire c'est:

- Le serveur reçoit une connexion
- Il se connecte à la DB
- Il fait sa requête

Ça marche, mais y'a 2 problèmes à ça:

1) Tu ouvres une connexion à la DB à chaque fois que quelqu'un accède à une page du site. C'est pas très optimisé. Ouvre la connexion **une seule fois** (au lancement de l'app), et ensuite réutilise cette connexion dans des callbacks de requêtes

2) La connexion à la DB ne se ferme jamais. C'est ce qu'on appelle une "Memory leak": ton application créé des ressources (ici des connexions DB) mais ne les "libère" jamais. Donc la mémoire grossit, grossit, et au bout d'un moment ton app va cracher

------------

Solution:

1) Créer la connexion DB quand tu lances ton app, tu créé ta variable `db` à ce moment là.
2) Quand ton serveur NodeJS s'éteint, tu `close` la connexion DB.

2019-07-30 08:40 UTC, jgabriele commented on public/semantic/style.css
> +#shopButton1, #shopButton2 {
En général je ne stylise jamais les `id`s. J'utilise des classes pour ça, les `id` c'est principalement pour target des éléments en JS

2019-07-30 08:40 UTC, jgabriele commented on views/layouts/shop/shopping.ejs
> +				<img src="<%= article.articleImage %>" alt="Une image d'otamatone">
Pourquoi le `alt` serait toujours le même ? ;)

`<img src="<%= article.articleImage %>" alt="<%= article.articleImageAlt %>">`

2019-07-30 08:40 UTC, jgabriele commented on views/layouts/shop/shopping.ejs
> +					<p>
Créé toi une carte sur Trello:

> Avoir la description des articles en DB, et en markdown

2019-07-30 08:41 UTC, Thibaut06 commented on app.js
> +app.get("/", (request, response) => {
MDR !

2019-07-30 08:41 UTC, Thibaut06 commented on app.js
> +        dbo.collection("articles").find().limit(3).toArray(getDataArticles)
Bien vu :/

2019-07-30 08:59 UTC, Thibaut06 commented on views/layouts/shop/shopping.ejs
> +					<p>
Validé, enfaite j'avais déjà les description des articles mais je l'ai pas implémenté -_-

2019-07-30 09:03 UTC, Thibaut06 commented on views/layouts/shop/shopping.ejs
> +				<img src="<%= article.articleImage %>" alt="Une image d'otamatone">
Done

2019-07-30 09:32 UTC, jgabriele commented on views/layouts/shop/shopping.ejs
> +					<p>
C'est pas une simple `string` en fait, si tu veux des sauts de ligne, des mots en gras, etc... Une simple `string` ne va pas suffire. Il faut utiliser du [markdown](https://fr.wikipedia.org/wiki/Markdown) (qui au final est une string mais tu formatte ton texte)

2019-07-31 19:59 UTC, jgabriele approved these changes
Good, mais garde la bonne habiture de virer les bouts de code commentés

2019-08-01 07:38 UTC, merged